### ISSUE TITLE
TimescaleDB configuration

### ISSUE THREAD

**Issue by basilfx** [nickbabcock/pg-collectd#116]
Thanks for this plugin. It works great on my Ubuntu 21.04 machine with PostgreSQL 13 and the TimescaleDB extension.

I've created [this](https://gist.github.com/basilfx/aa858a4c69ec3bb44c98061a50c63376) configuration to set-up the `collectd_metrics` table. It might be useful as a starting point for a section in the README.

**Comment by nickbabcock** [comment]
Great suggestion, I added your config to the readme.
